let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Versace",
    price: 23000,
    desc: " [IN STOCK] Versace a symbol of exquisite craftsmanship and luxury.",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Invicta reserve",
    price: 26000,
    desc: " [IN STOCK] Exceptional quality and style, making it a statement of sophistication and luxury.",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Edifice Casio",
    price: 21000,
    desc: " [IN STOCK]. Edifice by Casio embodies a fusion of style and precision, making it a testament to elegance and performance ",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Rolex",
    price: 16000,
    desc: "[IN STOCK]. Rolex gold plated silver, is synonymous with timeless luxury and exceptional craftsmanship",
    img: "images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Rolex",
    price: 16000,
    desc: "[IN STOCK] Available in Gold plated.",
    img: "/images/img-5.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Hublot Geneve",
    price: 17500,
    desc: "[IN STOCK] Epitomizes enduring opulence and unmatched artistry, with our exquisite timepieces now ready for acquisition.",
    img: "/images/img-6.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Hublot Geneve",
    price: 17500,
    desc: "[IN STOCK] Gold Colour",
    img: "/images/img-7.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Audemars Piguet ",
    price: 16000,
    desc: "[IN STOCK] Experience timeless luxury and craftsmanship with our available exquisite timepieces.",
    img: "/images/img-8.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Invicta Swiss reserve",
    price: 12000,
    desc: "[IN STOCK]As usual, discover affordable and stylish Swiss watches, from classic to innovative designs, in our collection.",
    img: "/images/img-9.jpg",
  },
  {
    id: "oiopijmjkuihb",
    name: "Invicta Swiss reserve",
    price: 16500,
    desc: "[IN STOCK] Comes with a quality leather bracelet",
    img: "/images/img-10.jpg",
  },
  {
    id: "oiopiwyiohbjhib",
    name: "Invicta Swiss reserve",
    price: 16500,
    desc: "[IN STOCK] Silver, Comes with a quality leather siver bracelet",
    img: "/images/img-11.jpg",
  },
  {
    id: "rtytytuyuytyybvncv",
    name: "i20 Ultra Max Suit",
    price: 27000,
    desc: "[IN STOCK] Comes with 7straps,Airpod,and pouch, full screen display",
    img: "/images/img-12.jpg",
  },
  {
    id: "rtytytuyuytyytbvn",
    name: "i20 Ultra Max Suit",
    price: 27000,
    desc: "Check out for different strap colours.",
    img: "/images/img-13.jpg",
  },
  {
    id: "rtytytuyuytyyttbvncv",
    name: "i20 Ultra Max Suit",
    price: 27000,
    desc: "Check out for different strap colours..",
    img: "/images/img-14.jpg",
  },
  {
    id: "rtytytuyuytyytjbvncv",
    name: "i8 Ultra",
    price: 16000,
    desc: "[IN STOCK] Comes with airpod two straps, full screen display",
    img: "/images/img-15.jpg",
  },
  {
    id: "rtytytuyuytyytbvkkncv",
    name: "i8 Ultra",
    price: 16000,
    desc: "Explore different colours, full screen display",
    img: "/images/img-16.jpg",
  },
  {
    id: "rtytytuyuytyytbvv",
    name: "i8 Ultra",
    price: 16000,
    desc: "Explore different colours, full screen display",
    img: "/images/img-17.jpg",
  },
  {
    id: "rtytytuyuytyycv",
    name: "Gucci",
    price: 20000,
    desc: "[IN STOCK] Gucci offers exclusive elegance and innovative designs. Explore our collection of luxury fashion and accessories",
    img: "/images/img-18.jpg",
  },
  {
    id: "rtytytuyuytbvncv",
    name: "Gucci",
    price: 20000,
    desc: "Explore different design of Gucci",
    img: "/images/img-19.jpg",
  },
  {
    id: "rtytuyuytyytbncv",
    name: "Gucci",
    price: 20000,
    desc: "Explore different design of Gucci",
    img: "/images/img-20.jpg",
  },
  {
    id: "rtytuyuytytbvncv",
    name: "Gucci",
    price: 20000,
    desc: "Explore different design of Gucci",
    img: "/images/img-21.jpg",
  },
  {
    id: "rtytytuyutyytbvcv",
    name: "SKMEI",
    price: 20000,
    desc: "[IN STOCK] Discover durable and trendy timepieces. Explore our collection of watches for style and reliability.",
    img: "/images/img-22.jpg",
  },
  {
    id: "rtytytuyuytyytbcv",
    name: "SKMEI",
    price: 20000,
    desc: "Explore different design",
    img: "/images/img-23.jpg",
  },
  {
    id: "rtytytuyuytyytbvcv",
    name: "SKMEI",
    price: 20000,
    desc: "Explore different design",
    img: "/images/img-24.jpg",
  },
  {
    id: "rtytytuyuytyytbvn",
    name: "SKMEI",
    price: 20000,
    desc: "Explore different design",
    img: "/images/img-25.jpg",
  },
  {
    id: "rtytytuyuytycv",
    name: "SKMEI",
    price: 20000,
    desc: "Explore different design",
    img: "/images/img-26.jpg",
  },
  {
    id: "rtytyuytyytbvncv",
    name: "SKMEI",
    price: 20000,
    desc: "Explore different design",
    img: "/images/img-27.jpg",
  },
  {
    id: "rtytytuytyytbvncv",
    name: "Festina",
    price: 14000,
    desc: "[IN STOCK] Gold Festina Chronograph: Shop now for precision and elegance, and make a statement with our collection of chronograph watches.",
    img: "/images/img-28.jpg",
  },
  {
    id: "rtytytuyuytyyvncv",
    name: "Festina",
    price: 14000,
    desc: "[IN STOCK] Silver plated Festina Chronograph: Shop now for precision and elegance, and make a statement with our collection of chronograph watches.",
    img: "/images/img-29.jpg",
  },
  {
    id: "rtytytuyuytyvncv",
    name: "CK",
    price: 17000,
    desc: "IN STOCK] Calvin Klein: Elevate your style with our iconic fashion and accessories. Explore the latest trends in our collection now.",
    img: "/images/img-30.jpg",
  },
  {
    id: "rtytytuyuytyvncv",
    name: "Hublot",
    price: 13500,
    desc: "For Black lovers.",
    img: "/images/img-31.jpg",
  },
  {
    id: "rtytytuytyytbvncv",
    name: "King Invicta",
    price: 25000,
    desc: "[IN STOCK] For Black lovers with a working chronograph",
    img: "/images/img-32.jpg",
  },
  {
    id: "rtytytuytyytbvcv",
    name: "King Invicta",
    price: 25000,
    desc: "With a working Chronograph",
    img: "/images/img-33.jpg",
  },
  {
    id: "rtytuyuytyytbvn",
    name: "Franck Muller",
    price: 22000,
    desc: "[IN STOCK] Franck Muller: Experience exquisite Swiss watchmaking. Discover our collection of fine timepieces, blending innovation and tradition.",
    img: "/images/img-34.jpg",
  },
  {
    id: "rtytuyuytyytbvn",
    name: "Franck Muller",
    price: 22000,
    desc: "Explore different colours",
    img: "/images/img-35.jpg",
  },
  {
    id: "rtytytuyuyytbvn",
    name: "Swish",
    price: 25000,
    desc: " [IN STOCK] Swish: Where innovation dances with elegance, creating a harmonious symphony of style and sophistication",
    img: "/images/img-36.jpg",
  },
  {
    id: "rtytuyutyytbvcv",
    name: "Forecst",
    price: 20000,
    desc: "[IN STOCK] Forecast: A compass for the future, guiding decisions with insights, helping us navigate the unknown with clarity and confidence.",
    img: "/images/img-37.jpg",
  },
  {
    id: "rtytuyuytyytbvv",
    name: "Mettle",
    price: 38000,
    desc: "[IN STOCK] Mettle; A symbol of enduring style and precision, seamlessly blending fashion with functionality, embodying inner strength in the face of adversity.",
    img: "/images/img-38.jpg",
  },
  {
    id: "rtytuyuytyytbvn",
    name: "Mettle",
    price: 38000,
    desc: "Explore another style of rose Gold",
    img: "/images/img-39.jpg",
  },
  {
    id: "rtytuyuyttbvncv",
    name: "Mettle",
    price: 38000,
    desc: "Explore another style of silver with rose Gold plated",
    img: "/images/img-40.jpg",
  },
  {
    id: "rtytyuyuytyyvncv",
    name: "Hublot",
    price: 18000,
    desc: "[IN STOCK] Hublot Chain Strap: Elevate your timepiece with a fusion of elegance and innovation, available now for an exquisite style upgrade.",
    img: "/images/img-41.jpg",
  },
  {
    id: "rtytyuyutyytbvncv",
    name: "Hublot",
    price: 18000,
    desc: "Explore different design",
    img: "/images/img-42.jpg",
  },
  {
    id: "rtytyytyytbvncv",
    name: "Hublot",
    price: 18000,
    desc: "Explore Rose Gold",
    img: "/images/img-43.jpg",
  },
  {
    id: "rtytytuyuytyytncv",
    name: "Hublot",
    price: 13000,
    desc: "explore more",
    img: "/images/img-45.jpg",
  },
  {
    id: "rtytytuyuytybvncv",
    name: "MontBlanc",
    price: 13000,
    desc: "[IN STOCK] MontBlanc: Elevate your writing experience with precision and luxury. Explore our collection of fine pens, now available for acquisition.",
    img: "/images/img-44.jpg",
  },
  {
    id: "rtytytuyuytyytbcv",
    name: "MontBlanc",
    price: 13000,
    desc: "More style",
    img: "/images/img-46.jpg",
  },
  {
    id: "rtytytuyuytyyv",
    name: "Emporio Armani",
    price: 14000,
    desc: "[IN STOCK] Emporio Armani: Where fashion meets sophistication. Explore our collection of timeless clothing and accessories for a touch of Italian elegance.",
    img: "/images/img-47.jpg",
  },
  {
    id: "rtytytuyuytbvncv",
    name: "Swiss Army Chronograph",
    price: 23000,
    desc: "[IN STOCK] Swiss Army Chronograph: Precision engineering meets rugged elegance. Explore our collection of reliable timepieces for a timeless style statement.",
    img: "/images/img-48.jpg",
  },
  {
    id: "rtytyyuytyytvncv",
    name: "RABO",
    price: 23000,
    desc: "[IN STOCK] Rabo: Where innovation meets elegance, forging a path to excellence with style that's always in season.",
    img: "/images/img-49.jpg",
  },
  {
    id: "rtytytuyuytbvncv",
    name: "Versace",
    price: 23000,
    desc: "[IN STOCK] Versace Rose Gold: Embody opulence and refinement with the timeless allure of rose gold, elevating your style to iconic levels.",
    img: "/images/img-50.jpg",
  },
  {
    id: "rtytytuyuytbvncv",
    name: "Audemars Piguet",
    price: 23000,
    desc: "[IN STOCK]AP (Audemars Piguet): Elevating watchmaking to an art form, where precision and luxury merge, setting the standard for horological excellence.",
    img: "/images/img-51.jpg",
  },
  {
    id: "rtytytuyuytyyooovncv",
    name: "Audemars Piguet",
    price: 23000,
    desc: "[IN STOCK] Explore the black face",
    img: "/images/img-52.jpg",
  },
  {
    id: "rtytytuyuytyy",
    name: "Rolex-Set",
    price: 19000,
    desc: "[IN STOCK] Rolex Sets for Couples: Timelessly elegant, these exquisite pairs of watches symbolize love, unity, and shared moments that last a lifetime.",
    img: "/images/img-53.jpg",
  },
  {
    id: "ruyuytyytbvncv",
    name: "Rolex-Set",
    price: 19000,
    desc: "[IN STOCK] Explore ,more",
    img: "/images/img-54.jpg",
  },
  {
    id: "rtyuyuytyytvncv",
    name: "Rolex-Set",
    price: 19000,
    desc: "[IN STOCK] explore silver with black face",
    img: "/images/img-55.jpg",
  },
  {
    id: "rtytytutbvncv",
    name: "Rolex-Set",
    price: 19000,
    desc: "[IN STOCK] Bohold the Rose Gold",
    img: "/images/img-56.jpg",
  },
];
